# Generated by Django 3.2.3 on 2021-06-29 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_session', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unname', models.CharField(max_length=50)),
                ('pName', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_of_checkup', models.CharField(max_length=50)),
                ('pMobile', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('pulse', models.CharField(max_length=50)),
                ('blood_pressure', models.CharField(max_length=50)),
                ('temprature', models.CharField(max_length=50)),
                ('spo2', models.CharField(max_length=50)),
                ('comorbidity_existing_disease', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='imgs')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Checkup_date', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('precscription', models.TextField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
