# Generated by Django 3.2.7 on 2021-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
